### ISSUE TITLE
How do I manually restore state?

### ISSUE THREAD

**Issue by Sinmok** [shaneriley/jquery_remember_state#13]
I've noticed that I can manually trigger a state save by calling .rememberState("save") which is great.

How do I prevent the plugin from automatically prompting to restore the state and being able to control when it happens manually, such as through an onclick event on another button?

There doesn't seem to be a .rememberState("restore_state");

Really what I'd like is a button that the user clicks to save the state and a button to restore, without any of the auto stuff happening.

**Comment by shaneriley** [comment]
It's been a long time since I've used the plugin, so I'll have to scan through it tomorrow to know if there's already a way to avoid the trigger. If not, it makes perfect sense to have that as a custom event that's triggered based on a configuration option.

**Comment by shaneriley** [comment]
I'm going to rewrite a portion of this soon to make it easier to call methods manually, since right now there's no way to trigger restore state without firing a click event on the notice dialog's anchor.
