### ISSUE TITLE
Form Array Elements

### ISSUE THREAD

**Issue by akuma12** [shaneriley/jquery_remember_state#2]
Hi Shane,

Nice little plugin! I noticed a tiny bug that prevents the plugin from working with form array elements, such as input type="text" name="foo[]"

On line 36 of the unpacked version, if you add escaped quotes around data[i].name, for example:

$e = $f.find("[name=\"" + data[i].name + "\"]");

This won't throw any uncaught exceptions to the console.

Unfortunately, I'm not sure how it will work on multiple arrayed elements of the same name.

Otherwise, very handy plugin!

**Comment by shaneriley** [comment]
Thanks for catching that. I'm just about to put it in a rails app, so that would have been a problem. Fixed with commit 7482bd58d619ff2b94d1189cd8037670f873fac3
