### ISSUE TITLE
Picking up invalid data

### ISSUE THREAD

**Issue by drywall** [shaneriley/jquery_remember_state#5]
I'm trying to glom this (largely excellent) plugin onto a form generated by a CMS I have little control over. Not sure what it is about this form, but when the plugin tries to save or recall data it winds up populating instance.$el with null objects or other undesirables. 

I had trouble parsing the code to figure out where and why these were occurring, so I slapped on some checks. In removeIgnored I had to do this:
              if (typeof input === 'object' && name === input.name) { delete values[j]; }

And in clickNotice I had to do this at the beginning on the for loop:
            if (typeof data[i] !== 'object' || data[i] == null) continue;

Hopefully I can look into this more later but I just wanted to flag that the logic for populating the array of values within the form seems slightly broken.

**Comment by drywall** [comment]
URL of the form in question is http://amplifierhub.caringbridge.org/stories/share.html if that's helpful.

**Comment by shaneriley** [comment]
I'll try to look into it today or tomorrow. If the first conditional prevents the null values from being saved, there should be no reason for the second conditional in clickNotice.

**Comment by shaneriley** [comment]
Pushed an updated version that should fix this issue. I was deleting the object that contained the name/value of the input to be ignored, but not the place in the original array of objects. This leaves a null pointer, which was causing your issues. Refined the ignore list checking and grepped the removed values out of the array before saving. Let me know if this fixes the issue.

**Comment by shaneriley** [comment]
I'm going to close this, but if you still encounter problems let me know.
