### ISSUE TITLE
checkboxes are unhappy

### ISSUE THREAD

**Issue by ghost** [shaneriley/jquery_remember_state#7]
(chrome at least) changes the value of checked checkboxes to 'on', which doesn't work as the filter on line 46.

This appears to do the trick?
        clickNotice: function(e) {
            var data = JSON.parse(localStorage.getItem(e.data.instance.objName)),
                $f = $(this).closest("form"),
                $e;
            for (var i in data) {
                $e = $f.find("[name=\"" + data[i].name + "\"]");
                if ($e.is(":radio")) {
                    $e.filter("[value=\"" + data[i].value + "\"]").prop("checked", true);
                }
                else if ($e.is(":checkbox") && data[i].value=='on') {
                    $e.filter("[name=\"" + data[i].name + "\"]").prop("checked", true);
                }
                else if ($e.is("select")) {
                    $e.find("[value=\"" + data[i].value + "\"]").prop("selected", true);
                }
                else {
                    $e.val(data[i].value);
                }
                $e.change();
            }
            e.data.instance.noticeDialog.remove();
            e.preventDefault();
        },

**Comment by shaneriley** [comment]
In my tests, checkboxes work fine in Chrome. See http://shaneriley.com/jquery/remember_state/ for an example. The value of the checkbox is going to be whatever the value of the input is. Inspecting the DOM object for the checkbox shows no sign of a property with a value of "on" that could be mistaken for the value of the checkbox.

I'm thinking this is a specific issue to a form you're working with. Can you create a demo reproducing the issue on somewhere like JSBin or JSFiddle?

**Comment by ghost** [comment]
I think this is it: http://jsbin.com/awebob/1/

**Comment by shaneriley** [comment]
That does it, though I'm wondering why you would have a checkbox without a value attribute. I think the full solution would be to ensure the value is truthy, and add checked to it if it is. I'll write a test and patch for it shortly. Thanks for the example.
