### ISSUE TITLE
TextArea not saving to local storage.

### ISSUE THREAD

**Issue by mikeamcbrien** [shaneriley/jquery_remember_state#8]
I just tried to implement this lovely little script on a project I am working on, works great for all of the form fields I have except for a textarea field. I troubleshot the script for a bit and thought i would read over things again.

I tried the textarea on your demo and it is also not working.

From my testing it appears that the textarea field is not identified as having a value/ or as an element, and it is never put into local storage

Tried using Chrome 27 on OSX, Firefox 21 OSX.  Firefox form data will persist on page reload, but if you close and reopen firefox all data except the textarea will populate.

-Mike

**Comment by shaneriley** [comment]
The demo is using the ignore option to specifically ignore the textarea. I just tested the demo page without the ignore and it remembers the textarea. Double check that you haven't copied that option in your implementation, and if not let me know where I can check out the code for the issue you're having.

**Comment by shaneriley** [comment]
Going to close this with the assumption that the issue was what was described in the previous comment. Please reopen and include an example demo if it's still not working.
